### ISSUE TITLE
psp.distributed.ini examples/library hangs with exception raised in pspsserver.py:1188

### ISSUE THREAD

**Issue by AdamVStephen** [AdamVStephen/hieratika#3]
18235792 L:<Lock(owner=None)> @ 140229186854864
[2018-01-14 18:44:08] [DEBUG] [18937] [140229186713344] [pspsserver.py:1014] Updating AA@BB@CC with value 3
[2018-01-14 18:44:08] [INFO] [18937] [140229186713344] [_internal.py:88] 127.0.0.1 - - [14/Jan/2018 18:44:08] "POST /savelibrary HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/adam/git-wd/hieratika/server/hieratika/wservermain.py", line 351, in savelibrary
    ret = wserver.saveLibrary(request)
  File "/home/adam/git-wd/hieratika/server/hieratika/wserver.py", line 574, in saveLibrary
    lib = self.serverImpl.saveLibrary(htype, name, description, username, variables)
  File "/home/adam/git-wd/hieratika/server/hieratika/servers/psps/pspsserver.py", line 1188, in saveLibrary
    ok = (len(updateVariable) > 0)
NameError: global name 'updateVariable' is not defined

**Comment by AdamVStephen** [comment]
Nice that the server keeps running and that the exception is trapped and logged.    The browser ends up with a spinning "Loading" panel though, for a long time.   Unclear if this is a bug in implemented code, or a gap in code yet to be implemented.

**Comment by AdamVStephen** [comment]
From the code it seems clear to be a trivial typo.  s/updateVariable/updatedVariable/g is the patch.
